name: CloudHub 1.0 deployment using Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeployToCH1:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code from Master branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and Deploy to CH 1.0
      run: mvn clean deploy -DmuleDeploy -s settings.xml -DworkerType=MICRO -Dworkers=1 -Dregion=us-east-2 -Denvironment=Dev -Dcloudhub.application.name=simi-cicd-poc -Denv.CONNECTEDAPP_CLIENTSECRET=0A98217eE7a74B79bef452473F2CA128 -Denv.CONNECTEDAPP_CLIENTID=a02ea545ffe6476a9b1d42fb035d1fc4 -Dmule.env=dev
