name: CloudHub 1.0 deployment using Maven

jobs:
  buildAndDeployToCH1:

    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENTID: ${{secrets.CONNECTEDAPP_CLIENTID}}
      CONNECTEDAPP_CLIENTSECRET: ${{secrets.CONNECTEDAPP_CLIENTSECRET}}
      
    steps:
    - name: Checkout the code from Master branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and Deploy to CH 1.0
      run: mvn clean deploy -DmuleDeploy -s settings.xml -DworkerType=MICRO -Dworkers=1 -Dregion=us-east-2 -Denvironment=Test -Dcloudhub.application.name=simi-cicd-poc -Dmule.env=test
